### ISSUE TITLE
impossible d'ouvrir certains fichiers video

### ISSUE THREAD

**Issue by Geress** [thomas-ernest/plugin.video.arteplussept#32]
J'ai un problème sur l'extension Arte+7 de Kodi. Certains fichiers trouvés dans le recherche ne peuvent pas s'ouvrir.
Voici l'adresse du fichier log : paste.kodi.tv/cuwejubodu
[hastebin - cuwejubodu.pdf](https://github.com/thomas-ernest/plugin.video.arteplussept/files/12813163/hastebin.-.cuwejubodu.pdf)

Pouvez-vous me dire quel est le problème, et aussi la solution.
Cordialement

**Comment by smihai** [comment]
Visiblement dans le commit b1d87643bb93806ad0c0a29ed367a98335f6f8be il a été oublié de passer le paramètre `plugin` dans la ligne:
`return mapper.map_collection_as_playlist(sibling_arte_items, program_id)` du fichier `resources/lib/view.py`.

Cela devrait être : 
`return mapper.map_collection_as_playlist(plugin, sibling_arte_items, program_id)`

**Comment by smihai** [comment]
J'ai créé la RP #33

**Comment by Geress** [comment]
Merci smihai. J'ai rajouté le paramètre "plugin", et les fichiers demandés s'ouvrent.

**Comment by thomas-ernest** [comment]
Hello,

Thank you for spotting this one. I integrated the fix in 1.4 release bracnh to be then delivered in 1.4.1.

PR in this repository : https://github.com/thomas-ernest/plugin.video.arteplussept/pull/36
PR so that version 1.4.1 including the fix got propagated to everyone : https://github.com/xbmc/repo-plugins/pull/4401

I will aslo merge your PR into master, because cascading from release/1.4 to master is not yet configured.
