### ISSUE TITLE
Addon states "Authentication needed in addon settings"

### ISSUE THREAD

**Issue by lje** [thomas-ernest/plugin.video.arteplussept#34]
Since 1 or 2 weeks the "Arte +7" addon states "Authentication needed in addon settings" and a lot of Arte videos do not play. What kind of authentication is needed? Did I miss that Arte needs some kind of login/account now to play videos?

**Comment by thomas-ernest** [comment]
Hello @lje ,

Authentication is needed with your account on https://www.arte.tv/ is you want to benefit from a full experience i.e. cross-device favorites, cross-device video progress, etc...
To authenticate, just go to addon settings, log in and out again. It is necessary to do that from time to time, when your authentication token expires.

You can still watch a lot of content if not all without being authenticated. The problem you encounter is not related to authentication, but to a bug in version 1.4.0. It has been logged with https://github.com/thomas-ernest/plugin.video.arteplussept/issues/32. It will be fixed with 1.4.1 available once integrated in official repository with https://github.com/xbmc/repo-plugins/pull/4401.

Is it clear or do you have any question please ? If it's ok please close the issue, you can always re-open it later if needed. Otherwise, let me know how I can help.

Thanks

**Comment by lje** [comment]
Hi @thomas-ernest, thanks for the reply. I indeed mixed up the two issues, I do not have an account and never had one. I understand that the issue is unrelated to accounts and therefore will wait for the update.
